### ISSUE TITLE
Thread Safety Error

### ISSUE THREAD

**Issue by erick-xanadu** [egraphs-good/egglog-python#128]
For the following code in google colab

```python
#!pip install egglog==6.0.1
from __future__ import annotations

from egglog import *

import numpy as np

egraph = EGraph()

str2mat = {
    "X" : np.array([[0., 1.], [1., 0.]]),
    "Y" : np.array([[0., 1j], [-1j, 0.]]),
    "Z" : np.array([[1., 0.], [0., -1.]]),
    "I" : np.array([[1., 0.], [0., 1.]])
}


class Op(Expr):
    def __init__(self, op_type: String) -> None:
        ...

    def __add__(self, other: Op) -> Op:
        ...

    def __mul__(self, other: Op) -> Op:
        ...

    def __matmul__(self, other: Op) -> Op:
        ...

@function
def commutes_with(self : Op, op1: Op) -> Bool: ...

@egraph.register
def _(a: Op, b : Op):
    yield rewrite(a @ b).to(b @ a, eq(commutes_with(a, b)).to(Bool(True)))

import itertools
with egraph:
  for i in itertools.permutations(["X", "I"], 2):
    op0 = Op(i[0])
    op1 = Op(i[1])
    egraph.register(set_(commutes_with(op0, op1)).to(np.allclose(str2mat[i[0]] @ str2mat[i[1]] - str2mat[i[1]] @ str2mat[i[0]], np.zeros((2,2)))))
  kron = egraph.let("stmt", Op("X") @ Op("I"))
  egraph.run(2)
  egraph.display()
```

I get the following non-deterministic error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/colab/_variable_inspector.py", line 27, in run
RuntimeError: egglog_python::conversions::Call is unsendable, but is being dropped on another thread
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/colab/_variable_inspector.py", line 27, in run
RuntimeError: egglog_python::conversions::Call is unsendable, but is being dropped on another thread
```

**Comment by saulshanabrook** [comment]
Thanks for opening this issue.


It looks like the Colab variable inspector is using another thread to access the data but the Rust constructs are not thread safe.

I will take a look into trying to make them threadsafe. Do you know if it's possible to disable the variable inspector in colab?

**Comment by saulshanabrook** [comment]
Could you try updating to `6.1.0` to see if that fixes it?

**Comment by erick-xanadu** [comment]
Hi @saulshanabrook! Thanks for the quick reply. I've tried it and it is still happening. It is non deterministic, but usually running a cell with:

```python
import itertools
with egraph:
  for i in itertools.permutations(["X", "I"], 2):
    op0 = Op(i[0])
    op1 = Op(i[1])
    egraph.register(set_(commutes_with(op0, op1)).to(np.allclose(str2mat[i[0]] @ str2mat[i[1]] - str2mat[i[1]] @ str2mat[i[0]], np.zeros((2,2)))))
  kron = egraph.let("stmt", Op("X") @ Op("I"))
  egraph.run(2)
  egraph.display()
```

around 5 times triggers the error message.

**Comment by erick-xanadu** [comment]
Sorry, never mind. This looks fixed! Maybe I just needed to restart the environment. Thanks!
